name = "Up Business Theme"
license = "MIT"
licenselink = "https://github.com/JulesTopart/hugo-up-business/blob/main/LICENSE"
description = "A clean and modern landing page website inspired by clean and modern illustrations."

homepage = "https://github.com/JulesTopart/hugo-up-business.git"

tags = ["blog", "responsive", "personal", "light", "tailwind", "portfolio", "landing", "company", "modern"]
features = []

[author]
  name = "Iago Bozza, Edited by Jules Topart"
